# Define default storage class. For DJ we want fast disk
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: anything
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd