# Default values for openam-dev.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into the templates

openamImage: forgerock/openam
#openamImage: gcr.io/engineering-devops/openam
openamImageTag: 14.0.0-SNAPSHOT

openamReplicaCount: 1

# Server base URL *within* the k8s cluster - not the external LB URL
# No /openam appended here.
serverBase: http://openam:80

# What OpenAM is known by *outside* the cluster - includes context root /openam
loadBalancerUrl: "https://openam.test.com:443/openam"

fqdnHostname: openam.test.com
cookieDomain: .test.com
amadmin_pw: password

openamInstance: http://openam:80/openam
configLdapPort:  389
configLdapHost: opendj-configstore-0.opendj-configstore

# Suffix for OpenDJ config store
rootSuffix:  "dc=openam,dc=forgerock,dc=org"

