apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: {{default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: openam
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
            "name": "copy",
            "image": "alpine",
            "command":  [ "/bin/sh", "-c",
            "cp /var/openam/boot/boot.json /root/openam; cp  -r /var/secrets/openam /root/openam/openam"],
            "volumeMounts": [
                        { "name": "openam-root",    "mountPath": "/root/openam" },
                        { "name": "openam-boot",    "mountPath": "/var/openam/boot" },
                        { "name": "openam-secrets", "mountPath": "/var/secrets/openam" }
                        ]}]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: openam
        image: {{ default "forgerock/openam" .Values.image}}:{{ default "latest" .Values.imageTag}}
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: openam-root
          mountPath: /root/openam
        # For slow environments like minikube you need to give openam time to come up
        readinessProbe:
          httpGet:
            path: /openam/isAlive.jsp
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /openam/isAlive.jsp
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 10
{{ if .Values.gkeLogging }}
      - name: log-collector
        image: gcr.io/google_containers/fluentd-sidecar-gcp:1.4
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
        env:
        - name: FILES_TO_COLLECT
          value: "/mnt/log/openam/log/*"
        volumeMounts:
        - name: openam-root
          readOnly: true
          mountPath: /mnt/log
{{- end }}
      volumes:
      - name: openam-root
        emptyDir: {}
      - name: openam-secrets
        secret:
          secretName: openam-secrets
      - name: openam-boot
        configMap:
          name: boot-json