apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: {{ .Values.djInstance }}
spec:
  serviceName: {{ .Values.djInstance }}
  replicas: {{default 1 .Values.replicaCount }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
        # Optional storage class here. This does not work seamlessly between minikube and gke right now
        #volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ default "5Gi"  .Values.storageSize }}
  template:
    metadata:
      labels:
        djInstance: {{ .Values.djInstance }}
      # This is a debug feature for Petsets. set to false and
      # the petset will pause before coming up
      # see http://kubernetes.io/docs/user-guide/petset/#what-is-a-petset
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: opendj
        image: {{ default "forgerock/opendj" .Values.djImage}}:{{ default "latest" .Values.djImageTag}}
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        resources:
          limits:
            memory: {{ default "1Gi" .Values.djMemoryLimit | quote}}
            cpu: {{  default "0.5" .Values.djCPULimit | quote }}
        env:
        - name: BASE_DN
          value: {{ default "dc=openam,dc=forgerock,dc=org" .Values.rootSuffix }}
        - name: DJ_MASTER_SERVER
          value: {{ .Values.djInstance -}}{{- "-0." -}}{{ .Values.djInstance }}
        - name: OPENDJ_JAVA_ARGS
          value: {{ default "-server -Xmx512m -XX:+UseG1GC" .Values.opendjJavaArgs | quote }}
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 4444
          name: djadmin
        volumeMounts:
        - name: dj-secrets
          mountPath: /var/secrets/opendj
        - name: data
          mountPath: /opt/opendj/data
      volumes:
      - name: dj-secrets
        secret:
          secretName: dj-secrets