# Default values for opendj.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value


dirManagerPassword: password

# djInstance name - this will be the statefull service name of DJ as well.
djInstance: opendj-configstore

# The number of instances in the petset. Each instance will be replicated to the master
replicaCount: 2

#djImage: forgerock/opendj

djImage: gcr.io/engineering-devops/opendj
djImageTag: 4.0.0-SNAPSHOT

#pullPolicy: Always
pullPolicy: IfNotPresent

# Size for DJ storage. Note GKE IOPS scale based on the size of the volume
storageSize: "10Gi"

# DJ tuning params. The amount of memory should be synced with memoryLimit below
opendjJavaArgs: "-server -Xmx2g -XX:+UseG1GC"

# Kubernetes memory limit for the pod. This should be a bit bigger than the heap size above
memoryLimit: "2500Mi"
# CPU limit - 1 GCP Core, 1 AWS vCPU. You can specify fractional value here
cpuLimit:  "1"